name: Markdown link scanner
description: Scans a folder of Markdown files for hyperlinks.
branding:
  icon: 'layers'
  color: 'purple'
inputs:
  path:
    description: The path to the file or directory to scan.
    required: true
  tool:
    description: The tool to use for scanning. Allowed values are 'markdig' and 'regex'.
    required: true
    default: 'markdig'
  outputHyperlinks:
    description: Output the hyperlinks found in the markdown files.
    required: false
    default: 'false'
outputs:
  markdown-summary:
    description: Summary of the results from the execution of the application.
runs:
  using: docker
  image: docker://ghcr.io/seesharprun/markdownscanperf:main
  args:
    - '--path'
    - ${{ inputs.path }}
    - '--tool'
    - ${{ inputs.tool }}
    - '--output-hyperlinks'
    - ${{ inputs.outputHyperlinks }}