name: Scan hyperlinks in Markdown files
on:
  workflow_dispatch:
    inputs:
      target-repository:
        description: The repository to run the scanner on in "owner/repo" format
        default: microsoftdocs/data-api-builder-docs
        required: true
        type: string
      output-hyperlinks:
        description: Output the hyperlinks found in the markdown files.
        default: false
        required: true
        type: boolean
jobs:
  run-scanner:
    name: Run hyperlink scanner
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      TARGET_REPOSITORY: ${{ github.event.inputs.target-repository || 'microsoftdocs/data-api-builder-docs' }}
      OUTPUT_HYPERLINKS: ${{ github.event.inputs.output-hyperlinks || false }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Checkout target repository [${{ env.TARGET_REPOSITORY}}]
        uses: actions/checkout@v4
        with:
          repository: ${{ env.TARGET_REPOSITORY}}
          path: target-repository
      - name: Write summary header
        run: |
          {
            echo "## Measurement summary :chart_with_upwards_trend:"
            echo " "
            echo "*Here's a summary of the hyperlink scan results for [${{ env.TARGET_REPOSITORY}}](https://github.com/${{ env.TARGET_REPOSITORY}}).*"
            echo " " 
          } >> $GITHUB_STEP_SUMMARY
      - name: Run hyperlink scanner
        uses: ./
        with:
          path: ./target-repository
          tool: markdig
          outputHyperlinks: ${{ env.OUTPUT_HYPERLINKS }}
      - name: Run hyperlink scanner
        uses: ./
        with:
          path: ./target-repository
          tool: regex
          outputHyperlinks: ${{ env.OUTPUT_HYPERLINKS }}
